import {useEffect,useRef,useState} from 'react';
import {NativeMotion} from './native';
import {Preparation,definition} from './model';
export default function MotionPanel({model,onReady}:{model:Preparation;onReady:(native:NativeMotion|null)=>void}){
 const ref=useRef<NativeMotion|null>(null);const [token,setToken]=useState('');
 useEffect(()=>{const native=new NativeMotion(model);ref.current=native;onReady(native);window.__btbNative=native;const params=new URLSearchParams(location.hash.slice(1)),pair=params.get('motion');if(pair){history.replaceState(null,'',location.pathname+location.search);void native.connect(pair);}return()=>{native.dispose();ref.current=null;onReady(null);delete window.__btbNative;};},[model,onReady]);
 const native=ref.current;
 return <section className="btb-motion"><h2>Move the MacBook. Move the glass.</h2><p>The local helper reads your MacBook’s inertial sensors. Keep the laptop still, recenter, then explicitly arm the glass. Browser play works without a helper.</p><p role="status">{native?.status??'Not connected'}{model.armed&&` · ARMED: ${model.armed==='pour'?model.stage==='mix'?definition.ingredients[model.selected].name:'Mixing glass pour':'Move glass'}`}</p>
  {!native?.connected&&<><a href="http://127.0.0.1:19876/pair" target="_blank" rel="noreferrer">Open local pairing page</a><details><summary>Pair manually</summary><label>Temporary pairing key<input type="password" value={token} autoComplete="off" onChange={e=>setToken(e.target.value)}/></label><button onClick={()=>{void native?.connect(token);setToken('');}}>Connect helper</button></details><p className="btb-hint">Start the provided native helper locally. If your browser asks, allow local network access for this site.</p></>}
  {native?.connected&&<><div className="btb-native-actions"><button onClick={()=>native.calibrate()}>Recenter at rest</button><button disabled={!native.calibrated} onClick={()=>model.armed?model.disarm():native.arm('move')}>{model.armed?'Disarm motion':'Arm glass movement'}</button>{['mix','strain'].includes(model.stage)&&<button disabled={!native.calibrated} onClick={()=>native.arm('pour')}>Arm pour</button>}<button onClick={()=>model.takeover()}>Use local controls</button><button onClick={()=>native.disconnect()}>Disconnect</button></div><p className="btb-hint">Gently tilt or briefly move the laptop, then stop. Escape, loss of focus, or 250 ms without samples disarms motion. Reconnection never rearms it.</p><details><summary>Motion diagnostics</summary><p>{native.received} real samples · {native.rejected} rejected · {Math.round(performance.now()-native.lastArrival)} ms since receipt</p><p>Relative pitch {(native.pitch-native.neutral[0]).toFixed(3)} rad · roll {(native.roll-native.neutral[1]).toFixed(3)} rad</p><p>Filtered linear acceleration {native.linear.map(n=>n.toFixed(2)).join(', ')} m/s²</p></details></>}
 </section>;
}
declare global {interface Window {__btbNative?:NativeMotion}}
