import {useCallback,useEffect,useRef,useState,useSyncExternalStore} from 'react';
import {ArrowLeft,ArrowRight,RotateCcw,Volume2,VolumeX,Move,Rotate3D,Hand,Plus,Minus,ChevronLeft} from 'lucide-react';
import {Preparation,COMPONENTS,definition,total,clamp} from './model';
import type {Preset} from './model';
import type {StudioScene} from './scene';
import Marble from '../components/Marble';
import './studio.css';
import MotionPanel from './MotionPanel';
import {StudioSound} from './audio';
import type {NativeMotion} from './native';
declare global {interface Window {__btb?:{model:Preparation;scene:StudioScene|null}}}
const stageNames={prepare:'A little ice first.',mix:'Find your balance.',stir:'Give it a little stir.',strain:'Make the pour yours.',express:'A bright finishing note.',garnish:'Your finishing touch.',serve:'Made your way.'};
function percent(n:number,max=1){return `${Math.round(n/max*100)}%`;}
export default function Studio(){
 const [model]=useState(()=>new Preparation(new URLSearchParams(location.search).get('preset')==='stir-demo'?'stir-demo':'start-empty'));
 useSyncExternalStore(model.subscribe,()=>model.revision);
 const nativeRef=useRef<NativeMotion|null>(null);const nativeReady=useCallback((native:NativeMotion|null)=>{nativeRef.current=native;},[]);
 const canvasRef=useRef<HTMLCanvasElement>(null),sceneRef=useRef<StudioScene|null>(null);
 const [status,setStatus]=useState('Preparing glass, ice & live liquid…'),[retry,setRetry]=useState(0),[mode,setMode]=useState<'stir'|'move'|'orbit'>('stir'),[reference,setReference]=useState(false),[about,setAbout]=useState(false),[motion,setMotion]=useState(location.pathname.includes('diagnostics')||location.hash.includes('motion='));
 const [muted,setMuted]=useState(()=>localStorage.getItem('btb-muted')==='true');const soundRef=useRef(new StudioSound());soundRef.current.setMuted(muted);
 function sound(kind:'ice'|'touch'='touch'){soundRef.current.unlock();if(kind==='ice')soundRef.current.clink(.6);}
 useEffect(()=>{let cancelled=false;let scene:StudioScene|null=null;window.__btb={model,scene:null};import('./scene').then(m=>m.createStudioScene(canvasRef.current!,model,s=>!cancelled&&setStatus(s),soundRef.current)).then(s=>{if(cancelled)s.dispose();else{scene=sceneRef.current=s;window.__btb={model,scene:s};}}).catch(e=>{if(!cancelled)setStatus(`Scene could not load. ${e instanceof Error?e.message:'Please retry.'}`);});return()=>{cancelled=true;scene?.dispose();sceneRef.current=null;delete window.__btb;};},[model,retry]);
 useEffect(()=>()=>soundRef.current.dispose(),[]);
 // Accounting remains usable when both rendering APIs are absent.
 useEffect(()=>{let last=performance.now();const timer=setInterval(()=>{const now=performance.now();if(!sceneRef.current&&!document.hidden){model.tick(Math.min((now-last)/1000,1/60));model.notify();}last=now;},16);return()=>clearInterval(timer);},[model]);
 const pointer=useRef<{id:number;x:number;y:number;angle:number;t:number}|null>(null);
 function release(){pointer.current=null;model.stirInput=0;model.pourTilt=0;model.move(0,0);model.notify();}
 function start(e:React.PointerEvent){if(model.stage==='serve'&&!reference){setMode('orbit');}model.takeover();const rect=e.currentTarget.getBoundingClientRect();pointer.current={id:e.pointerId,x:e.clientX,y:e.clientY,angle:Math.atan2(e.clientY-rect.top-rect.height*.5,e.clientX-rect.left-rect.width*.5),t:performance.now()};e.currentTarget.setPointerCapture(e.pointerId);sound();}
 function drag(e:React.PointerEvent){const p=pointer.current;if(!p||p.id!==e.pointerId)return;const rect=e.currentTarget.getBoundingClientRect(),now=performance.now(),dx=e.clientX-p.x,dy=e.clientY-p.y;
  if(mode==='orbit'||model.stage==='serve'){sceneRef.current?.orbit(-dx*.008,dy*.004);}
  else if(model.stage==='garnish'){model.pose({x:model.garnish.x+dx*.002,z:model.garnish.z+dy*.002});}
  else if(model.stage==='mix'||model.stage==='strain'){model.pour(clamp(.4-dy*.02+model.pourTilt,0,1));}
  else if(mode==='move'){model.move(dy*.006,dx*.006,dx*.035,dy*.035);}
  else {const angle=Math.atan2(e.clientY-rect.top-rect.height*.5,e.clientX-rect.left-rect.width*.5);const delta=Math.atan2(Math.sin(angle-p.angle),Math.cos(angle-p.angle));model.stir(clamp(delta/Math.max(.012,(now-p.t)/1000),-8,8),angle);p.angle=angle;if(Math.abs(model.stirInput)>1)sound('ice');}
  p.x=e.clientX;p.y=e.clientY;p.t=now;
 }
 function key(e:React.KeyboardEvent){if(e.key==='Escape'){release();model.disarm();return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' '].includes(e.key)){e.preventDefault();model.takeover();if(mode==='orbit'||model.stage==='serve'){sceneRef.current?.orbit(e.key==='ArrowLeft'?-.15:e.key==='ArrowRight'?.15:0,e.key==='ArrowUp'?.08:e.key==='ArrowDown'?-.08:0);}else if(model.stage==='garnish'){model.pose({x:model.garnish.x+(e.key==='ArrowLeft'?-.025:e.key==='ArrowRight'?.025:0),z:model.garnish.z+(e.key==='ArrowUp'?-.025:e.key==='ArrowDown'?.025:0)});}else if(['mix','strain'].includes(model.stage)){model.pour(.85);}else if(mode==='move'){model.move(e.key==='ArrowUp'?-.2:e.key==='ArrowDown'?.2:0,e.key==='ArrowLeft'?-.2:e.key==='ArrowRight'?.2:0);}else{model.stir(e.key==='ArrowLeft'?-4:4);}}}
 function openMotion(){setMotion(true);requestAnimationFrame(()=>document.getElementById('btb-motion-panel')?.scrollIntoView({block:'start'}));}
 function reset(preset?:Preset){release();model.reset(preset);setReference(false);setMode('stir');}
 const step=model.stage==='prepare'||model.stage==='mix'?0:model.stage==='stir'?1:model.stage==='strain'?2:3;
 const can=model.canAdvance();const isPour=['mix','strain'].includes(model.stage);
 return <div className="btb-shell">
  <header className="btb-header"><a className="sa-wordmark" href="/">SpiritAtlas</a><a className="btb-back" href="/?drink=negroni-express"><ArrowLeft size={16}/>Back to Bar Somma</a><button className="btb-icon" onClick={()=>{setMuted(!muted);localStorage.setItem('btb-muted',String(!muted));}} aria-label={muted?'Unmute sound':'Mute sound'}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></header>
  <main className="btb-main">
   <div className="btb-intro"><div><h1>Behind the bar<span>.</span></h1><p>{definition.label}</p></div><button className="btb-link" onClick={()=>setAbout(!about)} aria-expanded={about}>About this remix</button></div>
   {about&&<div className="btb-disclosure"><p>Make an illustrative remix of Negroni Express. Ancho Verde and rice syrup are named in the supplied film. Our unbranded core blend stands in for unresolved recipe details, excluding those separate modifiers. Every portion here is authored for play; Bar Somma’s exact recipe and measures are unpublished.</p><a href="/?drink=negroni-express&expand=1">Explore the source ingredients <ArrowRight size={15}/></a></div>}
   <div className="btb-workspace">
    <section className="btb-stage" aria-label="Interactive preparation">
     <div className="btb-marble"><Marble/></div>
     <div className="btb-stage-top"><span>NEGRONI EXPRESS / STUDIO</span>{model.origin==='demo'&&<span className="btb-demo">Prefilled live preview</span>}</div>
     {motion&&<div className="btb-live-motion">{nativeRef.current?.connected?<><span>{model.armed?`Armed · ${model.armed==='pour'?model.stage==='mix'?definition.ingredients[model.selected].name:'Mixing glass':model.armed==='stir'?'Stirring':'Move glass'}`:nativeRef.current.calibrated?'Laptop connected · disarmed':'Laptop connected · set it flat to calibrate'}</span>{!nativeRef.current.calibrated?<button onClick={()=>nativeRef.current?.calibrate()}>Calibrate</button>:<>{model.armed?<button onClick={()=>model.disarm()}>Disarm</button>:<>{model.stage==='stir'&&<button onClick={()=>nativeRef.current?.arm('stir')}>Arm stirring</button>}<button onClick={()=>nativeRef.current?.arm('move')}>Arm movement</button></>}{isPour&&!model.armed&&<button onClick={()=>nativeRef.current?.arm('pour')}>Arm pour</button>}</>}</>:<><span>Laptop tilt is off · helper not connected</span><button onClick={openMotion}>Pair laptop</button></>}</div>}
     <canvas ref={canvasRef} className="btb-canvas" tabIndex={0} aria-label="Live cocktail. Drag a circle to stir; use arrow keys or the controls beside the glass." onPointerDown={start} onPointerMove={drag} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release} onKeyDown={key} onKeyUp={release} onBlur={release}/>
     {reference&&<figure className="btb-reference"><img src="/references/negroni-express.png" alt="Bar Somma’s filmed red-orange Negroni Express, clear ice and curved green shishito"/><figcaption>Bar Somma’s presentation <button onClick={()=>setReference(false)}>Return to my remix</button></figcaption></figure>}
     <p className="btb-gesture-hint">{model.armed==='stir'?'Rock or turn the laptop to stir · hold still to settle':mode==='orbit'?'Drag to look around':model.stage==='stir'?mode==='move'?'Drag to move the glass':'Drag a circle to stir':isPour?'Drag down to tilt · release to pause':model.stage==='garnish'?'Drag to position the pepper':model.stage==='serve'?'Drag to look around':'Your ingredients, your way'}</p>
     <div className="btb-scene-tools"><div className="btb-mode" aria-label="Gesture mode">{(['stir','move','orbit'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>{release();model.takeover();setMode(m);}}>{m==='stir'?<Hand size={16}/>:m==='move'?<Move size={16}/>:<Rotate3D size={16}/>}<span>{m==='stir'?'Tools':m==='move'?'Move glass':'Look around'}</span></button>)}</div><div className="btb-zoom"><button aria-label="Zoom out" onClick={()=>sceneRef.current?.zoom(-.1)}><Minus size={16}/></button><button aria-label="Zoom in" onClick={()=>sceneRef.current?.zoom(.1)}><Plus size={16}/></button></div></div>
     <p className="btb-render-status" role="status">{status}{status.includes('could not')&&<button onClick={()=>setRetry(n=>n+1)}>Retry scene</button>}</p>
    </section>
    <section className="btb-controls" aria-label="Preparation controls">
     <ol className="btb-progress" aria-label="Preparation progress">{['Mix','Stir','Pour','Finish'].map((label,i)=><li key={label} aria-current={i===step?'step':undefined}><span>{i+1}</span>{label}</li>)}</ol>
     <div className="btb-step-copy" aria-live="polite"><h2>{stageNames[model.stage]}</h2><p>{model.stage==='stir'?model.armed==='stir'?'Gently rock or turn the laptop. Reverse the movement to change direction, then hold still and let it settle.':'Drag a circle around the glass. Reverse direction, then let it settle.':model.message}</p></div>
     {model.stage==='prepare'&&<button className="btb-primary" onClick={()=>{model.addIce();sound('ice');}}>Add mixing ice <Plus size={18}/></button>}
     {model.stage==='mix'&&<div className="btb-ingredients">{COMPONENTS.map((c,i)=><button key={c} className="btb-ingredient" aria-pressed={model.selected===c} onClick={()=>model.select(c)}><span className="btb-bottle-mark" style={{'--liquid-color':definition.ingredients[c].color,'--source-fill':percent(model.sources[c],definition.ingredients[c].initial)} as React.CSSProperties}><i/></span><span><strong>{definition.ingredients[c].name}</strong><small>{i===0?'Unbranded prepared blend':'Optional modifier'}</small></span><span className="btb-portion">{percent(model.sources[c],definition.ingredients[c].initial)}<small>left</small></span></button>)}</div>}
     {isPour&&<div className="btb-pour-control"><label htmlFor="btb-tilt">{model.stage==='mix'?definition.ingredients[model.selected].name:'Mixing glass'} tilt <output>{Math.round(model.pourTilt*70)}°</output></label><input id="btb-tilt" type="range" min="0" max="1" step=".01" value={model.pourTilt} onPointerDown={()=>model.takeover()} onChange={e=>{model.takeover();model.pour(+e.target.value);model.notify();}}/><button className="btb-primary" onClick={()=>{const active=model.pourTilt>.2;model.takeover();model.pour(active?0:.85);model.notify();sound();}}>{model.pourTilt>.2?'Pause pour':'Pour'} <ArrowRight size={17}/></button><p className="btb-hint">Click to pour, click again to pause. Every drop stays yours.</p></div>}
     {model.stage==='stir'&&<div className="btb-stir-controls"><div className="btb-two"><button onPointerDown={()=>{model.takeover();model.stir(-3);sound('ice');}} onPointerUp={release} onPointerLeave={release} onBlur={release} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();model.takeover();model.stir(-3);}}} onKeyUp={release}>Hold to stir left</button><button onPointerDown={()=>{model.takeover();model.stir(3);sound('ice');}} onPointerUp={release} onPointerLeave={release} onBlur={release} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();model.takeover();model.stir(3);}}} onKeyUp={release}>Hold to stir right</button></div><p className="btb-advice">{model.effectiveStir>5?'Smooth circulation. Ready when you are.':model.effectiveStir>1?'Try changing direction.':'Slow circles. Then a little faster.'}</p><p className="btb-hint">Stirring guidance is optional. You can strain whenever you like.</p></div>}
     {model.stage==='express'&&<><button className="btb-primary" onClick={()=>{model.express();sound();}}>{model.oil?'Expressed':'Express orange oil'} <Plus size={17}/></button><p className="btb-hint">Squeeze the peel over the surface. The peel doesn’t stay in the glass.</p></>}
     {model.stage==='garnish'&&<div className="btb-garnish"><p>Drag to position the pepper, or use these controls.</p>{[['x','Across the rim',-.2,.2],['z','Front to back',-.22,.22],['angle','Rotate pepper',-3.14,3.14]].map(([key,label,min,max])=><label key={key as string}>{label}<input type="range" min={min} max={max} step=".01" value={model.garnish[key as 'x'|'z'|'angle']} onChange={e=>model.pose({[key]:+e.target.value})}/></label>)}<button className="btb-primary" onClick={()=>{model.pose({placed:true});sound();}}>{model.garnish.placed?'Pepper placed':'Place pepper'}</button></div>}
     {model.stage==='serve'&&<div className="btb-result"><h3>{model.origin==='demo'?'Demo serving':'Your studio remix'}</h3><p>{percent(total(model.serving),definition.capacity.serve)} of the studio glass · {model.oil?'Orange oil expressed':'Without orange oil'}</p><ul>{COMPONENTS.map(c=><li key={c}><span>{definition.ingredients[c].name}</span><strong>{percent(model.serving[c]/total(model.serving))}</strong></li>)}</ul><p className="btb-hint">Illustrative mixture shares, not the bar’s recipe.</p><button onClick={()=>setReference(!reference)}>{reference?'Return to my remix':'Compare with Bar Somma’s presentation'}</button><button className="btb-primary" onClick={()=>reset('start-empty')}>Try another mix <ArrowRight size={17}/></button><a href="/?drink=negroni-express">Return to the real drink <ArrowRight size={15}/></a></div>}
     {model.stage!=='prepare'&&model.stage!=='serve'&&<div className="btb-next"><button className="btb-link" onClick={()=>model.back()} disabled={model.stage==='mix'||model.transit.length>0||model.pourTilt>.01}><ChevronLeft size={16}/>Back</button><button className="btb-next-button" disabled={!can} onClick={()=>{model.advance();setMode('stir');}}>{model.stage==='mix'?'Stir':model.stage==='stir'?'Strain':model.stage==='strain'?'Finish pouring':model.stage==='express'?model.oil?'Place garnish':'Skip oil':model.stage==='garnish'?'Serve':''}<ArrowRight size={17}/></button></div>}
     {model.stage!=='prepare'&&<div className="btb-ledger"><div><span>In the mixing glass</span><strong>{percent(total(model.mix),definition.capacity.mix)}</strong></div><div className="btb-fill"><i style={{width:percent(total(model.mix),definition.capacity.mix)}}/></div>{model.servingIce&&<><div><span>In your serving</span><strong>{percent(total(model.serving),definition.capacity.serve)}</strong></div><div className="btb-fill"><i style={{width:percent(total(model.serving),definition.capacity.serve)}}/></div></>}<small>Illustrative fill · amounts remain when you go back</small></div>}
    </section>
   </div>
   <footer className="btb-footer"><button className="btb-link" onClick={()=>reset()}><RotateCcw size={15}/>{model.preset==='stir-demo'?'Reset demo':'Start over'}</button>{model.origin==='demo'?<button className="btb-link" onClick={()=>reset('start-empty')}>Start my remix <ArrowRight size={15}/></button>:<button className="btb-link" onClick={()=>reset('stir-demo')}>Try stirring</button>}<button className="btb-link btb-motion-entry" onClick={openMotion} aria-expanded={motion} aria-controls="btb-motion-panel">{motion?'Motion setup':'Enable laptop motion'} <Move size={15}/></button></footer>
   {motion&&<MotionPanel model={model} onReady={nativeReady}/>}
  </main>
 </div>;
}
