import {test,expect} from '@playwright/test';
import {Preparation,total,definition,COMPONENTS} from '../src/behind-the-bar/model';
function tick(p:Preparation,seconds:number){for(let i=0;i<seconds*120;i++)p.tick(1/120);}
function pour(p:Preparation,seconds:number){p.pour(.85);tick(p,seconds);p.pour(0);tick(p,.2);}
function conserved(p:Preparation){for(const c of COMPONENTS)expect(Math.abs(p.conservation()[c])).toBeLessThan(1e-9);for(const q of [p.sources,p.mix,p.serving])for(const c of COMPONENTS)expect(q[c]).toBeGreaterThanOrEqual(0);}
test('three sources, pause/resume, partial strain, omitted modifier and saved result',()=>{const p=new Preparation();expect(p.advance()).toBe(false);p.addIce();pour(p,1);const partial=p.sources.core;tick(p,1);expect(p.sources.core).toBe(partial);pour(p,1);expect(p.sources.core).toBeLessThan(partial);p.select('ancho');pour(p,.4);expect(p.mix.rice).toBe(0);expect(p.advance()).toBe(true);expect(p.effectiveStir).toBe(0);expect(p.advance()).toBe(true);pour(p,.9);const remains=total(p.mix);expect(remains).toBeGreaterThan(0);expect(p.advance()).toBe(true);expect(p.advance()).toBe(true);p.pose({x:.12,z:-.1,angle:1.1,placed:true});expect(p.advance()).toBe(true);expect(p.result?.garnish).toEqual(p.garnish);expect(p.result?.components).toEqual(p.serving);expect(p.result?.origin).toBe('user');expect(total(p.mix)).toBe(remains);conserved(p);});
test('exhaustion, capacity and transit never lose or create components',()=>{const p=new Preparation();p.addIce();for(const c of COMPONENTS){p.select(c);pour(p,15);conserved(p);}expect(total(p.mix)).toBeCloseTo(definition.capacity.mix,7);p.advance();p.advance();pour(p,20);expect(total(p.serving)).toBeCloseTo(definition.capacity.serve,7);expect(total(p.mix)).toBeCloseTo(.15,7);expect(p.ice).toBe(3);conserved(p);});
test('demo uses legal accounting, reset clears input without normalizing user results',()=>{const p=new Preparation('stir-demo');expect(p.mix).toEqual(definition.baseline);conserved(p);p.armed='pour';p.stir(5);tick(p,2);p.reset();expect(p.armed).toBeNull();expect(p.stirInput).toBe(0);expect(p.effectiveStir).toBe(0);expect(p.origin).toBe('demo');p.reset('start-empty');expect(total(p.mix)).toBe(0);expect(p.origin).toBe('user');conserved(p);});
test('idle or impulse does not earn readiness; early straining is legal',()=>{const p=new Preparation('stir-demo');tick(p,10);expect(p.effectiveStir).toBe(0);p.move(.2,.1,3,2);tick(p,1);expect(p.effectiveStir).toBe(0);expect(p.canAdvance()).toBe(true);p.stir(3);tick(p,6);expect(p.effectiveStir).toBeGreaterThan(5);p.disarm();tick(p,1);expect(p.effectiveStir).toBeLessThan(6.01);});
test('invalid values and invalid stage intents do not contaminate state',()=>{const p=new Preparation();p.pour(Infinity);p.stir(NaN);p.pose({x:NaN,angle:Infinity});p.move(NaN,Infinity,NaN,-Infinity);tick(p,1);conserved(p);expect(p.vesselX).toBe(0);expect(p.result).toBeNull();});
